version: '3'

services:
    # backend:
    #     build: ./backend
    #     restart: unless-stopped
    #     mem_limit: '64M'
    #     cpus: 0.25
    #     volumes:
    #         - ./backend:/app
    #     ports:
    #         - 10000:10000
    #     command: npm start
    # frontend:
    #     build: ./frontend
    #     restart: unless-stopped
    #     mem_limit: '64M'
    #     cpus: 0.25
    #     volumes:
    #         - ./frontend:/app
    #     ports:
    #         - 10010:80
    #     env_file:
    #         - frontend/.env
    #     environment:
    #         PORT: 10010
    # ai-server:
    #     build: ./ai-server
    #     restart: unless-stopped
    vulnerable-machine:
        build:
            context: ./vulnerable-machine
            dockerfile: DebianDockerfile
        restart: unless-stopped
        hostname: "vulnerable"
        tty: true
        ports:
            - "2022:22"
    attacker-machine:
        build:
            context: ./attack-machine
            dockerfile: DebianDockerfile
        restart: unless-stopped
        hostname: "attack"
        tty: true
        ports:
            - "1022:22"
    db:
        image: postgres
        command: postgres -c 'max_connections=500'
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres_user
            - POSTGRES_PASSWORD=postgres_pass
